name: "action-openapi2confluence"
description: "Action that read openapi file and export to confluence"

inputs:
  path: 
    description: 'path to openapi file'
    required: true
  id: 
    description: 'confluence page id'
    required: true
  spaceKey: 
    description: 'space that page is inside'
    required: true
  ancestorId: 
    description: 'parrent page'
    required: true
  title: 
    description: 'title of page'
    required: true
  localId: 
    description: 'localid'
    required: true
  macroId: 
    description: 'macroId'
    required: true
  env: 
    description: 'envorriment that runnings'
    required: true
  confluenceHost:
    description: 'set the confluence url'
    required: true
  confluenceAuth:
    description: 'basic auth for api confluence'
    required: true
  confluenceEmail:
    description: 'email user of confluence'
    required: true

runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  env:
    OPENAPI2CONFLUENCE_CONFLUENCE_API_KEY: ${{ inputs.confluenceAuth }}
    OPENAPI2CONFLUENCE_CONFLUENCE_EMAIL: ${{ inputs.confluenceEmail }}
    OPENAPI2CONFLUENCE_CONFLUENCE_HOST: ${{ inputs.confluenceHost }}
  args:
    - ${{ inputs.path }}
    - ${{ inputs.id }}
    - ${{ inputs.spaceKey }}
    - ${{ inputs.ancestorId }}
    - ${{ inputs.title }}
    - ${{ inputs.localId }}
    - ${{ inputs.macroId }}
    - ${{ inputs.env }}


