name: tests
on:
  pull_request:
    branches:
      - production

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Run test
        run: go test -v ./...
